name: Build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.2
      - name: Get dependencies
        run: |
          go install -v ./...
      - name: Pre Commit
        run: make pre-commit
      - name: Build
        run: make build
